// Tests with synthetic media (generated by ffmpeg into a temp dir). Run: npm test
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { run, FFMPEG, probeVideo, detectShots, detectStale, analyzeEnvelope, reconcileBoundaries, cutSegments, renderKeep } from '../index.js';

let dir, burstFile, cutsFile;

before(async () => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'shot-cutter-test-'));
  // 12 s clip: quiet noise floor (-60 dB) with three "speech" bursts at 2–4 s, 6–6.8 s and 9–11 s.
  burstFile = path.join(dir, 'bursts.mp4');
  const tone = "0.25*sin(2*PI*300*t)*(between(t,2,4)+between(t,6,6.8)+between(t,9,11))+0.001*sin(2*PI*50*t)";
  await run(FFMPEG, ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=gray:s=320x240:r=30:d=12', '-f', 'lavfi', '-i', `aevalsrc='${tone}':s=48000:d=12`,
    '-shortest', '-c:v', 'libx264', '-preset', 'ultrafast', '-c:a', 'aac', burstFile]);
  // 9 s clip with hard cuts at 3 s and 6 s (three solid colors).
  cutsFile = path.join(dir, 'cuts.mp4');
  await run(FFMPEG, ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=red:s=320x240:r=30:d=3', '-f', 'lavfi', '-i', 'color=c=blue:s=320x240:r=30:d=3',
    '-f', 'lavfi', '-i', 'color=c=green:s=320x240:r=30:d=3', '-filter_complex', '[0][1][2]concat=n=3:v=1:a=0', '-c:v', 'libx264', '-preset', 'ultrafast', cutsFile]);
});

after(() => fs.rmSync(dir, { recursive: true, force: true }));

test('library import has no side effects and exposes the API', () => {
  for (const fn of [probeVideo, detectShots, detectStale, cutSegments, renderKeep]) assert.equal(typeof fn, 'function');
});

test('probeVideo reports fps from avg_frame_rate and audio presence', async () => {
  const p = await probeVideo(burstFile);
  assert.ok(Math.abs(p.fps - 30) < 0.01);
  assert.equal(p.hasAudio, true);
  assert.ok(Math.abs(p.duration - 12) < 0.2);
});

test('detectStale keeps the three bursts and removes the silence', async () => {
  const r = await detectStale(burstFile);
  assert.equal(r.keep.length, 3, JSON.stringify(r.keep));
  const expect = [[2, 4], [6, 6.8], [9, 11]];
  r.keep.forEach((k, i) => {
    assert.ok(k.start <= expect[i][0] && k.start >= expect[i][0] - 0.35, `start ${k.start}`);
    assert.ok(k.end >= expect[i][1] && k.end <= expect[i][1] + 0.4, `end ${k.end}`);
  });
  assert.ok(r.stats.keptRatio < 0.6);
});

test('analyzeEnvelope merges pauses shorter than minSilence', () => {
  const frameSec = 0.02, db = new Float32Array(500).fill(-70);
  for (let i = 100; i < 150; i++) db[i] = -20;   // 2.0–3.0 s
  for (let i = 160; i < 210; i++) db[i] = -20;   // 3.2–4.2 s (0.2 s gap → merged)
  const r = analyzeEnvelope({ frameSec, db, duration: 10 });
  assert.equal(r.keep.length, 1);
});

test('reconcileBoundaries does not chain distinct nearby cuts', () => {
  const c = [0.9, 0.95, 1.0, 1.05, 1.1, 1.15].map((time) => ({ time, detector: 'scdet' }));
  const b = reconcileBoundaries(c, 10, { tolerance: 0.06, gap: 0.12 });
  assert.ok(b.length >= 2, `expected ≥2 boundaries, got ${b.length}`);
});

test('detectShots finds the two hard cuts', async () => {
  const r = await detectShots(cutsFile);
  assert.equal(r.boundaries.length, 2);
  assert.ok(Math.abs(r.boundaries[0].time - 3) < 0.1 && Math.abs(r.boundaries[1].time - 6) < 0.1);
});

test('cutSegments splits in one pass at the given times', async () => {
  const out = path.join(dir, 'shots');
  await cutSegments(cutsFile, [3, 6], out, { preset: 'ultrafast', stripAudio: true });
  const files = fs.readdirSync(out).filter((f) => f.endsWith('.mp4')).sort();
  assert.deepEqual(files, ['1.mp4', '2.mp4', '3.mp4']);
  for (const f of files) { const p = await probeVideo(path.join(out, f)); assert.ok(Math.abs(p.duration - 3) < 0.15, `${f}: ${p.duration}`); }
});

test('renderKeep concatenates kept ranges', async () => {
  const out = path.join(dir, 'tight.mp4');
  await renderKeep(burstFile, [{ start: 2, end: 4 }, { start: 9, end: 11 }], out, { preset: 'ultrafast' });
  const p = await probeVideo(out);
  assert.ok(Math.abs(p.duration - 4) < 0.2, `duration ${p.duration}`);
});
